CREATE DATABASE campus;

CREATE TABLE campers(
    id INT primary key AUTO_INCREMENT,
    NOMBRES VARCHAR (50) NOT NULL,
    DIRECCION VARCHAR (50) NOT NULL,
    LOGROS VARCHAR(60),
    SKILL INT,
    INGLES VARCHAR (15),
    SER INT ,
    REVIEW VARCHAR (10),
    ESPECIALIDAD VARCHAR (10),

);
